publish_to: none
name: test_rtc
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  #  flutter_webrtc:
  #    path: local_plugins/flutter_webrtc-0.13.1+hotfix.1
  flutter_webrtc:
    path: plugins/flutter-webrtc-main
  web_socket_channel: ^3.0.3
  permission_handler: ^11.0.0
  flutter_lints: ^2.0.0
  flutter_foreground_task: ^6.1.2
  my_phone_blocker:
    path: local_plugins/my_phone_blocker
  shared_preferences: ^2.5.3
  http: ^1.3.0
  flutter_easyloading: 3.0.5 #loading
  adaptive_dialog: ^2.1.0 # 自动适配的弹窗,底部sheet等
  gesture_x_detector: ^1.1.1
  android_intent_plus: ^5.3.0
  flutter_overlay_window: ^0.5.0
  wakelock_plus: ^1.3.2
  screen_brightness: ^2.1.2
  device_info_plus: ^11.5.0
  #  agora_rtc_engine: ^6.5.1
#  byteplus_rtc: ^3.56.3
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true