name = "yunzhutong-web"
compatibility_date = "2024-07-20"

# Cloudflare Pages配置 - 适合静态Flutter Web应用
pages_build_output_dir = "build/web"

# 环境配置
[env.production]
name = "yunzhutong-web-prod"
# 如果有自定义域名，取消注释并修改
# routes = [
#   { pattern = "your-domain.com/*", zone_name = "your-domain.com" }
# ]

[env.preview]
name = "yunzhutong-web-preview"

# 环境变量
[vars]
ENVIRONMENT = "production"
APP_NAME = "云协通Web主控端"
VERSION = "1.0.0" 